[Container]
Image=ghcr.io/domini/nginx_with_dav-ext-module:latest
Mount=
Mount=type=volume,source=nginx-dav-config@.volume,target=/etc/nginx,ro
Mount=type=tmpfs,target=/var/cache/nginx,chown,tmpfs-mode=1755
Mount=type=tmpfs,target=/run/nginx,chown,tmpfs-mode=1755
